version: '3.7'
services:
 
  qmware2_app:
    image: san0123/centos8-apache24-php73
    container_name: qmware2_app
    volumes:
      - ./qmware2:/var/www/html
    working_dir: /var/www/html  
    restart: always
    ports:
      - 80:80
 
  qmware2_db:
    image: mysql:5.6
    container_name: qmware2_db
    volumes:
      - ./qmware2/sql/db_init.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${QMWARE_DB_ROOT}
      MYSQL_DATABASE: ${QMWARE_DB}
      MYSQL_USER: ${QMWARE_DB_USER}
      MYSQL_PASSWORD: ${QMWARE_DB_PASSWORD}
